version: '3.8'

services:
  k6-performance-test:
    image: grafana/k6:latest
    environment:
      - K6_CLOUD_TOKEN=${GRAFANA_CLOUD_TOKEN}  # Replace with your actual token
      - BASE_URL=${BASE_URL}        # Load from .env
    volumes:
      - ./performance_test.js:/performance_test.js  # Mount test script
    command: ["run", "/performance_test.js", "-o", "cloud"]  # Runs test locally but sends output to Grafana Cloud
