version: '3.8'

services:
  k6-performance-test:
    image: grafana/k6:latest
    environment:
      - K6_CLOUD_TOKEN=${GRAFANA_CLOUD_TOKEN}  # Replace with your actual token
      - BASE_URL=${BASE_URL}        # Load from .env
    volumes:
      - .:/k6-test  # Mount the entire directory
    working_dir: /k6-test  # Set working directory inside the container
    command: ["run", "/k6-test/performance_test.js", "-o", "cloud"]